### ISSUE TITLE
LCE doesn't use the stated amount of n_jobs

### ISSUE THREAD

**Issue by nikita68** [LocalCascadeEnsemble/LCE#1]
Hello,

I'm loving LCE up until now! One thing I've noticed is that LCE does not follow the amount of jobs stated, and uses all processors.

I believe the issue comes from stating 'n_jobs=-1' in the config of xgboost, [example here](https://github.com/LocalCascadeEnsemble/LCE/blob/d08521491770a4dab1f8ae57351a0492da294eb6/lce/_xgboost.py#L223). A fix should be relatively straightforward by just passing this variable on.

Cheers,
Nikita

**Comment by LocalCascadeEnsemble** [comment]
Hello,

Thank you for your message and I confirm that I have changed it in the version 0.2.4.

Best,
