### ISSUE TITLE
requirements.txt strict equality

### ISSUE THREAD

**Issue by fitzgeraldja** [LocalCascadeEnsemble/LCE#7]
Is it possible to change requirements.txt (and setup.py) from requiring exact equality in supporting packages? It can cause conflicts with other packages, and it's not clear if this is actually required - you could use pipreqs with mode gt for instance if there are no breaking changes in more recent versions.

**Comment by LocalCascadeEnsemble** [comment]
Hello,

Thank you for your message.   

Unfortunately, I have tried and encountered some errors with the latest version of the required packages
This configuration is the one I found to ensure compatibility.
However, I will continue to test the new versions of the required packages to propose the most recent configuration possible.

Best,
